### ISSUE TITLE
Conflict with Shadersmod creates a display issue when the Snitch Visualizer is active

### ISSUE THREAD

**Issue by Coftheo** [Scuwr/Snitch-Visualizer#2]
Turning on the Snitch Visualizer feature of this mod while running Shadersmod causes a gray filter to be displayed over some visual elements. The hotbar and visual elements from other modifications do not appear to be affected. 

Sample screenshot: https://i.imgur.com/5dwhnOt.png
Comparison Photo: https://i.imgur.com/mOUZytr.png

I've confirmed the issue with the version named: 'ShadersModCore-v2.3.18-mc1.7.10-f1179.jar'. I did not load a shaderpack for the issue to occur. If you're not familiar with Shadersmod, it allows for individual shaderpacks to be used, among other things. Here's a link to the minecraftforum thread: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286604-shaders-mod-updated-by-karyonix

Distance to registered snitches or having registered snitches in range does not appear to affect this issue. 

Mods other than Shadersmod on the list [here](https://i.imgur.com/2EJtzMg.png) do not appear to cause issues. I'm using "1.7.10-Forge10.13.2.1230". 

I don't think it's an issue related to differences between graphics cards either. The grey filter showed up when I ran Shadersmod alongside the snitch visualizer. It didn't seem to matter whether I used my integrated or discrete graphics card. 

Adapted from this Reddit comment thread: https://www.reddit.com/r/Civcraft/comments/321c6b/mod_scuwrs_snitch_visualizer_v11/cq8lxuk?context=10000

**Comment by Scuwr** [comment]
I have been trying to replicate the issue, but I just can't seem to be able to at all. I'm using ShadersModCore-v2.3.18-mc1.7.10-f.jar. Perhaps you need to update the mod since I've noticed that I am using a different version than you. Also, I am using the SEUS shaderpack and everything is fine.

**Comment by Coftheo** [comment]
Alright, I'll update my FML and I'll try out the new Shadersmod file. 

What version of Forge are you using?

**Comment by Coftheo** [comment]
I've tested my client with the new version of Shadersmod posted, and the issues stopped appearing for both this mod, and for Squeenix's old mod. 

I did not update Forge. 

It's weird that the developer did not increment the version with the the new version of the file. 

Now that my problem is solved I'm closing the issue. It's highly likely that only Shadersmod is to blame with this conflict.
