### ISSUE TITLE
Version increment causes prior version snitch list to be missed by loader

### ISSUE THREAD

**Issue by ProgrammerDan** [Scuwr/Snitch-Visualizer#3]
Haven't tested this to be sure, but a casual read of the snitch list loading code shows that the version change in SV will cause the list loader to look for a 1.1.0 - named list instead of what will exist for those who used the interim version, namely, a 1.0.1 or 1.0.2 list. I did not observe any code to address this.

I'm probably going to work on a port of this codebase to use sqlite to store snitch data and also /jainfo data shortly, which should remove this issue moving forward. 

Otherwise, it'll be necessary to include a check routine that searches for prior version snitch log files and progress them along with the version of the mod.

**Comment by Scuwr** [comment]
The lists aren't tagged by version number, the update to the number was so
the mod shows the proper version number when the player inspects the mods
they have enabled. I'm not exactly seeing the issue here, so if there is
one, could you please elaborate?

**Comment by ProgrammerDan** [comment]
_Edit_: Yeah, filename doesn't include version, but file-path does, so same result:

https://github.com/Scuwr/Snitch-Visualizer/blob/master/src/main/java/com/github/scuwr/snitchvisualizer/handlers/SVFileIOHandler.java#L28

New snitchlist storage file includes the version:

https://github.com/Scuwr/Snitch-Visualizer/blob/master/src/main/java/com/github/scuwr/snitchvisualizer/SV.java#L41

Previously it was this:

https://github.com/Scuwr/Snitch-Visualizer/blob/080329389caf1641a2bfbfe72000c77a58ebac7a/src/main/java/com/github/scuwr/snitchvisualizer/SV.java#L41

Ergo, there is no logic to migrate the file's name from the prior version to the new version, so the new file will be empty of snitches.

**Comment by Scuwr** [comment]
Ahh, sorry I see it now. I'll get to work on it.

**Comment by Scuwr** [comment]
I've been thinking about this, and now I'm not so sure different version folders would be necessary. If the data were to change between versions, it would be simple enough to make the file operations backwards compatible in the same way that was done between 1.0 and 1.1 instead of worrying about version changes in the directory. What do you think?

Also, please forgive my previous statements, I'm currently in a very sleep deprived state.

**Comment by ProgrammerDan** [comment]
Well, you're embarking on a journey of requiring migrations without there being a migration if you keep the version number as part of the path under which you store snitch data. E.g. on startup, the application has to query _every prior version's storage area_ to see if there is snitch data to migrate. Alternatively, don't have the application migrate snitches, and leave it to the user via instructions in the README. 

I'd recommend trying to avoid this migration problem, especially when the data definition hasn't changed. 

Alternatively, you might consider adding or appending a line to the snitch CSV indicating the version of snitch-visualizer that generated the file, and using that information to trigger a migration, if necessary.

**Comment by Coftheo** [comment]
You might be able to use something like XML or another (custom?) tag-based language to make data storage easier across different versions. Data could be stored in a common location with this scheme. 

For example, a snitch can be given different attributes, like location and group name. These attributes can be kept constant throughout versions, without need for changes. More data recorded by newer versions can be appended as new attributes.

**Comment by ProgrammerDan** [comment]
I'm not sure how Scuwr wants to move forward with this, but I intend to refactor all the storage components into a lightweight local SQLite DB. I'd love something heavier with GIS functionality, but SQLite should do the trick and scale fairly well to large numbers of snitches. We could probably also do something clever with some old techniques I know involving constrained spacial searching to make the layout of the database better and easier to search, potentially in log(n) time (even with 3D volumes). I'll have to dust off my old research notes.

**Comment by Coftheo** [comment]
SQLite seems like a good choice. 

What do you mean by GIS functionality?

**Comment by ProgrammerDan** [comment]
GIS is Geographic Information System -- PostGIS is the one I've worked with, and is an "engine" for use within the PostgreSQL infrastructure allowing super efficient lookups against geographic information. Some advanced systems can handle 3D queries as well. 

The searching techniques I mentioned are based on cell-reduction techniques I nearly wrote a paper on during my PhD studies for use in location co-presence searching; I think they'd be very useful in this context.

**Comment by Coftheo** [comment]
So that's what GIS means. Fancy. 
Can you explain the search techniques you plan to use in simpler language to me? I specifically want to know what cell-reduction techniques and co-presence searching are.  I'm somone with little knowledge in the field of computer science.

**Comment by ProgrammerDan** [comment]
Are you familiar with Bucket Sort / Bin Sort?

If not, quick summary: 

For a sortable set of items whose extent is constrained (say, whole numbers from 0 to 10000), you can use a very very efficient ( It's O(n) -- the fastest possible for sorting ) sort called Bucket sort, where items are successively shuffled into a fixed number of buckets. Because the number of buckets is known and fixed, it, like all constant factors in Order-of notation, can be "ignored", resulting in O(n) running time for the sort. 

Well, it's possible to leverage a similar idea with geographic volumes (3D spaces). Minecraft makes it even easier since the 3D volume we are considering is already well-constrained. Although it can grow "forever" radially, it is perfectly constrained vertically, and easily subdivided into volumes. So, we can effectively "presort" snitches into buckets whose index can be directly computed, allowing very fast identification of nearby snitches for updating, addition, etc. If each bucket is a volume 16x16x16 (a "chunk") then at most it could contain 4096 snitches and will most definitely contain far fewer than that; so we know that within an index bucket we have to compare against at most 4096 entries. Since the index can be computed directly, and we know the absolute upper bound of comparisons within each bucket, we have know it will take at most 4096 comparisons (a constant factory) to find a matching snitch during a search, or O(1) lookups (can't beat it. Period.) 

The cool thing about this is, since snitch radius is 10.5 blocks (effective), there's a expectation of 8 snitches per index bucket; so we're likely going to do just 8 comparisons per bucket. Now that should be very fast indeed.

There are other things we can do, and the above analysis assumes a carefully configured data structure that wouldn't be present in your average database (let alone, we might not want to use that much memory to "load" the full set of snitches into the custom data structure we would need), so practically speaking our search would be O(ln(n)) or, a logarithmic time lookup (still really fast) if we are using database indices. Why? Well, even if we can directly compute the index, the database won't keep every entry in active memory, so it will use a binary search to "track down" the data we want. Binary search is O(ln(n)). As we discussed, the subsequent search is linear, or O(1) so our total search is O(ln(n)). 

I'm not sure if that's simpler language, but I hope it's ... clearer. Was it? Sometimes I get lost in technicals.

**Comment by Scuwr** [comment]
Sorry for the late response, they keep us pretty busy at the Academy.

However, correct me if I am wrong, but the only advantage I can see for
implementing a complex database like liteSQL or mySQL is the representation
and support for related tables.

Currently as my plan stands, I have no desire nor any need for related
tables since the only data that I want to ever be automatically stored is
the snitch attributes. The snitch info for entries and block places can be
handled by just the current Minecraft instance as I do not desire for that
data to persist.

I do plan in the future to have a manual report feature, but at this time I
see it unnecessary to make that an automated function. Additionally I plan
on adding a block place/remove visualization, but again I don't see a need
to have that information persist beyond the current game instance.

Lastly, I was finally able to fix the binsearch algorithm for detecting
when the player enters the snitch area. It is now a hybrid search algorithm
binsearching for the right x-bounds and then testing the small list one by
one. I decided to finally do this since I could find no real accurate way
to sort a 3d array of field boundaries which in essence makes the array a
6d array when taking into account that there is an upper and lower boundary
for each axis.

If you feel otherwise, please let me know. Also, awesome synopsis of a
bucket sort!

**Comment by ProgrammerDan** [comment]
I don't disagree. I think for your goals any more advanced DB would be overkill. I have other goals, though :P. At some point our codebases might diverge more sharply, although at this point my ideas are specious. 

I might take a stab at replacing your arraylist<> with a more complex, but more efficient to search, data structure. That would at least be directly beneficial.

**Comment by Scuwr** [comment]
Close to another release, I got rid of the folder version issue and will put a readme in a .zip file with the .jar, so I'm closing this issue.
