### ISSUE TITLE
Auto-update triggers /jainfo

### ISSUE THREAD

**Issue by ProgrammerDan** [Scuwr/Snitch-Visualizer#5]
Not sure what's going on, but when entering a snitch field, /jainfo appears to be triggered. Could be related to report functionality.

**Comment by ProgrammerDan** [comment]
Note: relates to v.1.8-SNAPSHOT

**Comment by Scuwr** [comment]
That's supposed to happen. The list now keeps track of snitch names it does
not know. It should never be triggered again once it has already done so
once.

**Comment by ProgrammerDan** [comment]
Ahh, it appear to be retriggering. I will investigate.

**Comment by ProgrammerDan** [comment]
Thinking this through, it might be only during snitch coverage overlap. I'll do some more focused testing, now that I know what I'm looking at.

**Comment by Psomguy** [comment]
So does this mean snitch visualizer will always automatically check the logs of a snitch when you enter the snitch field? Not sure if I'd always want this on, especially if I have to run all over a city while talking in a group chat; it would spam the chat like crazy.

**Comment by ProgrammerDan** [comment]
It will, if the "report" function is turned on. I'd recommend leaving it off while you expect to chat. It's also very much a feature-in-development, so expect its behavior to change as Scuwr tweaks and improves it!

**Comment by Psomguy** [comment]
I'm not sure how to turn it off.

**Comment by ProgrammerDan** [comment]
Go into the options panel for snitch visualizer -- check your "key bindings" in Minecraft to see which key it's bound to -- and make sure the report function is turned off. (It's the middle-left button the options screen, currently). I'll post a screenshot tonight if you still can't find it.

**Comment by Psomguy** [comment]
The only button I see with the word "report" in it is "Generate Snitch Report". It doesn't seem to do anything.

**Comment by staygroovy57** [comment]
@Psomguy I think ProgrammerDan meant the "AutoUpdate" On/Off toggle switch. (rather than "Report ON/OFF")

**Comment by ProgrammerDan** [comment]
Thanks groovy, that is exactly what I meant.

**Comment by Psomguy** [comment]
Thanks, that helps

**Comment by ProgrammerDan** [comment]
Ok, tracked it down. The name update was getting stuck,  causing updates to issue for the same snitch every tick. Added some mire aggressive boolean resetting and the problem is resolved. Behavior is now as expected, snitch name is requested once.
