### ISSUE TITLE
Snitches aren't rendering

### ISSUE THREAD

**Issue by ProgrammerDan** [Scuwr/Snitch-Visualizer#6]
Still have to do more testing to see if this is only my machine, but snitches are not rendering at all. Figured I'd toss up the issue in case someone else is experiencing the same problem. I've gotten other issue reports, but nothing actionable yet.

**Comment by staygroovy57** [comment]
Same issue as ProgrammerDan here, I can update the list, and everything appears set the way it needs to be but I have yet to see any snitches. When I pass next to one of my snitches it displays the results of /jainfo so I know it's working.

Also, I cannot edit the list of snitches or scroll down, their names on the first page of this list all show as 'unknown'. In that "list' menu clicking on the 'Done' button does nothing, only hitting [Escape] lets me out of the "list snitches' menu.  (IGN: fk_54)

**Comment by ProgrammerDan** [comment]
Basic rendering should be fixed; @staygroovy57 can you download the latest release and confirm? The list of snitches should still be broken, for now. That's next on my list.

**Comment by staygroovy57** [comment]
Hey PG, thanks so much for looking into this, and yes I can confirm that rendering is now happening as it should.
